flags: {}
resolver: lts-19.5
extra-deps:
- attoparsec-data-1.0.4.1
- hw-prim-bits-0.1.0.4
- attoparsec-time-1


allow-newer: true
packages:
- .
- ../auris-tmph
- ../gui-base
- ../esa-base 
- ../esa-space-protocols
- ../mcs-interface 
- ../esa-mib
- ../esa-db

